---
driver:
  name: docker
  use_sudo: false

platforms:
  - name: centos-6.8

suites:
  - name: default
    run_list:
      - recipe[tomcat-liatrio::default]
    attributes:
      java:
        jdk_version: "8"
