
---
driver:
  name: docker
  use_sudo: false

platforms:
  - name: centos-7.2

driver_config:
  require_chef_omnibus: 12.16.42
  provision_command: 'yum install initscripts -y'
  run_command: '/usr/sbin/init'
  privileged: true

suites:
  - name: default
    run_list:
      - recipe[tomcat-liatrio::default]
    attributes:
      java:
        jdk_version: "8"
