default['tomcat_liatrio']['version'] = '8.0.32'
default['tomcat_liatrio']['tarball_base_path'] = 'http://archive.apache.org/dist/tomcat/'
default['tomcat_liatrio']['checksum_base_path'] = 'http://archive.apache.org/dist/tomcat/'
default['tomcat_liatrio']['connector_port'] = '8080'
default['tomcat_liatrio']['ajp_port'] = '8009'
